revert dependency upgrades from native app merge
attempting to fix strange runtime js error:
Error: Failed to execute 'removeChild' on 'Node':
The node to be removed is not a child of this node